<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import{ref}from'vue';import{api}from'./api';
const password=ref('');const result=ref(null);const audits=ref([]);const error=ref('');
const form=ref({requestId:'REQ-'+Date.now(),templateName:'客服政策回复',version:'v1.0.0',templateText:'请依据{{policy}}回答：{{question}}',policy:'七日内未拆封可退',question:'如何办理退款？',qualityScore:.92,safetyScore:.96,regressionPassRate:.98,estimatedCostPer1kTokens:.01,maxCostPer1kTokens:.03,ownerId:'prompt-owner',approverId:'business-approver'});
async function evaluate(){error.value='';try{const f=form.value;result.value=(await api('/api/promptops/releases/evaluate',{method:'POST',password:password.value,body:{...f,variables:{policy:f.policy,question:f.question},requiredVariables:['policy','question'],approved:true}})).data;}catch(e){error.value=e.message;}}
async function loadAudits(){try{audits.value=(await api('/api/promptops/audits',{password:password.value})).data;}catch(e){error.value=e.message;}}
</script>
<template><div class="shell"><aside><div class="brand">ZH <span>PromptOps</span></div><nav>发布工作台<br>模板版本<br>回归评测<br>成本治理<br>审计记录</nav><a href="https://www.zhuatech.cn/" target="_blank">知华科技官网</a></aside><main><header><div><small>AI 工程平台 / 提示词发布</small><h1>提示词发布控制台</h1></div><div class="auth"><input v-model="password" type="password" placeholder="管理员密码"><button class="secondary" @click="loadAudits">读取审计</button></div></header><section class="metrics"><article><b>5</b><span>联合发布门禁</span></article><article><b>95%</b><span>最低回归通过率</span></article><article><b>100%</b><span>发布操作留痕</span></article></section><div class="grid"><section class="panel"><h2>发布评估</h2><label>模板名称<input v-model="form.templateName"></label><label>版本<input v-model="form.version"></label><label>提示词模板<textarea v-model="form.templateText"></textarea></label><div class="cols"><label>政策变量<input v-model="form.policy"></label><label>问题变量<input v-model="form.question"></label></div><div class="cols"><label>质量分<input v-model.number="form.qualityScore" type="number" step=".01"></label><label>安全分<input v-model.number="form.safetyScore" type="number" step=".01"></label></div><button @click="evaluate">执行发布门禁</button><p class="error">{{error}}</p></section><section class="panel result"><h2>评估结果</h2><template v-if="result"><div class="decision" :class="result.decision.toLowerCase()">{{result.decision}}</div><p>风险：{{result.riskLevel}} · {{result.approvalRoute}}</p><h3>阻断项</h3><ul><li v-for="x in result.blockers">{{x}}</li></ul><h3>渲染结果</h3><pre>{{result.renderedPrompt||'阻断后不输出可发布提示词'}}</pre></template><p v-else class="empty">提交左侧版本后显示真实评估结果</p></section></div><section class="panel audit"><h2>最近审计</h2><table><thead><tr><th>请求</th><th>决策</th><th>风险</th><th>操作者</th><th>时间</th></tr></thead><tbody><tr v-for="x in audits"><td>{{x.requestId}}</td><td>{{x.decision}}</td><td>{{x.riskLevel}}</td><td>{{x.createdBy}}</td><td>{{x.createdAt}}</td></tr></tbody></table></section></main></div></template>
